# Generated by Django 4.1.5 on 2023-01-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='order',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
    ]
